### ISSUE TITLE
System inconsistently generated data record on Google drive and sending out emails HIGH PRIORITY

### ISSUE THREAD

**Issue by Bill-Chan** [CCLIFE/cclife-conf-registration-01#102]
This problem had been observed since Wenesday (7/29)

![img_2106](https://cloud.githubusercontent.com/assets/11229968/9010913/eb9e8046-3777-11e5-9108-2c7785df6bbc.png)

**Comment by chehhoo** [comment]
Modified report generating for entire registration for every half hour, this should fix data inconsistent issue. Test the email delivery during credit card checkout process, verify work in development. Turn on logging in test to monitor email in test. Updated in 8/3/2015
