### ISSUE TITLE
Step 1>>Family and Personal Data (2/16/2016 release)

### ISSUE THREAD

**Issue by Bill-Chan** [CCLIFE/cclife-conf-registration-01#11]
(a) County and state/Province heading should be indent several spaces to the right for ease reading.
(b) If someone  has selected  US (  Canada), province ( State) in Canada (US) should not be displayed
(c) Should not allow to enter any data if the attendee has  already entered address in US or Canada

**Comment by chehhoo** [comment]
Completed
