### ISSUE TITLE
Step 2>>Enter individual information (2/16/2016 release)

### ISSUE THREAD

**Issue by Bill-Chan** [CCLIFE/cclife-conf-registration-01#12]
(a) Why don’t we  allow the user to select more than one language?
(b) Should  Grade and Status are separate  questions?
 (c) )事奉角色 should not have status selection

**Comment by chehhoo** [comment]
a) Multiple language is not in scope. Please update business document if this requirement.
b) Temporary remove status but keep grade. Do office need status, tracking in business document.
c) Fixed
