### ISSUE TITLE
Step 1>> step 2>> Review Registration Summary

### ISSUE THREAD

**Issue by Bill-Chan** [CCLIFE/cclife-conf-registration-01#13]
“Previous” button always bring back to step 1, does not allow to go back to individual   information page.

**Comment by chehhoo** [comment]
Per activity diagram

When you are on page 3, previous will bring back to page 1 to edit address and primary information. To edit individual information. A button will created to go to individual profile page for making changes.

Please see this diagram

UML activity diagram
https://drive.google.com/file/d/0B4HEfjT8JXYxOUh5SGJlVXVURW8/view

Source code repository
https://github.com/CCLIFE/cclife-conf-registration-01/wiki

Close this issue, will create a new issue to track create the edit button
