### ISSUE TITLE
Text and format for page step2

### ISSUE THREAD

**Issue by weicai2015** [CCLIFE/cclife-conf-registration-01#32]
1. put firstname before lastname.
2. for gender field, put more space between male and female.
3. add words explaining "Only 18 and under requires grade."
4. for relationship field, the first person should be "Primary".
5. for language field, the list should be bilingual.
6. for headphone field, need add explaining message "If you don't understand Maindarin, you can choose interpret headphone."
7. for beliver field, change to "Christian" and add space between yes and no.
8. for serve role field, change to "church involve" and add an indicating letter at the beginning of list choices.
9. change wording for volunteer to "I want to volunteer to serve the conference."
10. change prompt wording of meal order.
11. for meal order, add "select all" button.
12. adding explain workding "the new added person should have the same address as the primary person."

**Comment by chehhoo** [comment]
completed
