### ISSUE TITLE
"Pay Now"  payment page.

### ISSUE THREAD

**Issue by weicai2015** [CCLIFE/cclife-conf-registration-01#34]

**Comment by Bill-Chan** [comment]
We may need to modification the instruction, easier for users to follow.....

**Comment by chehhoo** [comment]
Modify according this

![94b447ee35000d63a3b1571d6712a498](https://cloud.githubusercontent.com/assets/9040501/8687464/1e5990e0-2a56-11e5-8685-f2cb326e84fb.jpg)

**Comment by Bill-Chan** [comment]
Should be fixed with issue #85
