### ISSUE TITLE
Added validation on form 1

### ISSUE THREAD

**Issue by chehhoo** [CCLIFE/cclife-conf-registration-01#4]
Added validation code to make sure registrants filled all required fields about address, contact information, etc

**Comment by chehhoo** [comment]
Please add validation of form here 

com\cclife\registration\validator\FormValidator.java

Reference:-
http://docs.spring.io/spring-webflow/docs/2.4.x/reference/htmlsingle/#view-validate

Implementing a Validator

The second way is to define a separate object, called a Validator, which validates your model object. To do this, first create a class whose name has the pattern ${model}Validator, where ${model} is the capitialized form of the model expression, such as booking. Then define a public method with the name validate${state}, where ${state} is the id of your view-state, such as enterBookingDetails. The class should then be deployed as a Spring bean. Any number of validation methods can be defined. For example:

@Component
public class BookingValidator {
    public void validateEnterBookingDetails(Booking booking, ValidationContext context) {
        MessageContext messages = context.getMessageContext();
        if (booking.getCheckinDate().before(today())) {
            messages.addMessage(new MessageBuilder().error().source("checkinDate").
                defaultText("Check in date must be a future date").build());
        } else if (!booking.getCheckinDate().before(booking.getCheckoutDate())) {
            messages.addMessage(new MessageBuilder().error().source("checkoutDate").
                defaultText("Check out date must be later than check in date").build());
        }
    }
}

In the example above, when a transition is triggered in a enterBookingDetails view-state that is editing a Booking model, Web Flow will invoke the validateEnterBookingDetails(Booking, ValidationContext) method automatically unless validation has been suppressed for that transition.

A Validator can also accept a Spring MVC Errors object, which is required for invoking existing Spring Validators.

Validators must be registered as Spring beans employing the naming convention ${model}Validator to be detected and invoked automatically. In the example above, Spring 2.5 classpath-scanning would detect the @Component and automatically register it as a bean with the name bookingValidator. Then, anytime the booking model needs to be validated, this bookingValidator instance would be invoked for you.

Default validate method

A Validator class can also define a method called validate not associated (by convention) with any specific view-state.

@Component
public class BookingValidator {
    public void validate(Booking booking, ValidationContext context) {
        //...
    }
}

In the above code sample the method validate will be called every time a Model of type Booking is validated (unless validation has been suppressed for that transition). If needed the default method can also be called in addition to an existing state-specific method. Consider the following example:

@Component
public class BookingValidator {
    public void validate(Booking booking, ValidationContext context) {
        //...
    }
    public void validateEnterBookingDetails(Booking booking, ValidationContext context) {
        //...
    }
}

In above code sample the method validateEnterBookingDetails will be called first. The default validate method will be called next.

5.10.3. ValidationContext

A ValidationContext allows you to obtain a MessageContext to record messages during validation. It also exposes information about the current user, such as the signaled userEvent and the current user's Principal identity. This information can be used to customize validation logic based on what button or link was activated in the UI, or who is authenticated. See the API Javadocs for ValidationContext for more information.

**Comment by weicai2015** [comment]
Cheh:
Thanks for this email!
I got fresh new master version this afternoon. I tried it. I got this error at the very first begging:
----------------------------------javax.persistence.PersistenceException: [PersistenceUnit: registrationDatabase] class or package not found
java.lang.ClassNotFoundException: ws.cccm.application.model.Payment------------------------------------
Can you please look into this and let me know what I need to do?
Thanks.
Wei

**Comment by chehhoo** [comment]
Sorry, I left some file with old package name. Please update your code base
and try again.

**Comment by chehhoo** [comment]
This is done
