### ISSUE TITLE
 three fields for age under 18 

### ISSUE THREAD

**Issue by chehhoo** [CCLIFE/cclife-conf-registration-01#60]
Those three fields for age under 18 are not really required to be under 18, they are open to everyone, which is not the intention. I'm not sure why they are there, because the hard copy doesn't mention any of those.

**Comment by Bill-Chan** [comment]
To simplify this: we should just have one group: for under 18 for example "0-17".
also, to be consistent with the paper registration, we should change to: 18-30;31-40;41-50;51-60; 61+

**Comment by chehhoo** [comment]
Questions from email

Wei Cai to me, Bill

8:29 PM
Cheh, Bill:

I don't quite understand issue60. It is about "three fields for under 18", please tell me which three fields. Are they the health card number and allergy ? These two fields were added according to Xiaowei, she said for Canadian these two are very important for kids, so one of them is required for all under 18 and another is required for age 13 to 18.  I don't know which field is the third field mentioned in the issue. Please let me know.

And, for age group list, since there are at least two fields are required for age 13 to 18, one is personal email address, the other one is one I mentioned above, so I think to simplify the age group list to have only 0-17 won't work for these two fields, how about we do one group 0-12 and another group 13 - 18?

Thanks,
Wei

**Comment by chehhoo** [comment]
Wei,

I log this issue for Xiaobin, we can check with him to clarify.

My idea is use Javascript to hide/unhide the three fields questions if user select the age group as teenager, same function for email and confirmation email. This will avoid confusion.

We need confirm with conference management about group under 18 uder 2 group. We might not able to do this because the conference need exact age to grouping in children or youth program.

Cheh

**Comment by Bill-Chan** [comment]
Please ignore my comments 5 days ago.....my misunderstanding

**Comment by Bill-Chan** [comment]
added clarification with "Canadian Only"

![7837c5d917f63675f46ab0c47d3c8195](https://cloud.githubusercontent.com/assets/9040501/8687512/9ae8b8b6-2a56-11e5-85d0-6f83f8b0d9fa.jpg)
