### ISSUE TITLE
Page 2 confirmed email field

### ISSUE THREAD

**Issue by chehhoo** [CCLIFE/cclife-conf-registration-01#61]
"confirmed email" should not be empty. In fact, those info belong to the first page, and can be omitted.

**Comment by chehhoo** [comment]
The confirmed email is here to be filled up by youth. So, our validation will enforce registrants between age 13-18 to fill up the email fields. because this is wanted by youth director for youth related communication.

<b>Enhancement will be at later to hide this emails and confirmation email if the registrants are not teenager.</b>

**Comment by Bill-Chan** [comment]
Fixed
