### ISSUE TITLE
CC payment page frozen

### ISSUE THREAD

**Issue by xiaobin15** [CCLIFE/cclife-conf-registration-01#63]
How to produce the bug?

(1) click on CC button to pay by CC
(2) click on submit, errors say that some fields are missing
(3) click on back to home page

Then a blank page appears forever.

**Comment by chehhoo** [comment]
Thanks for the report.

Questions about reproduce the error? Do you pay by using test account or use credit card.

If pay by cards, please use this test cards

Fake card number:4032030255181654
Card type:VISA
Expiration date:05/2020
phone number:4088759440
email:cclife-buyer@sbcglobal.net

Some note: When on paypal side, we lost control of the registration flow, click back will lose the registration data. This might be the reason you see blank page forever. We added 警告before go to paypal side. Here is one of the warining

請勿點擊瀏覽器的<b>退回鍵</b>,以免丟失您所有信息

If there is missing fields, user have to resolve by checking each fields on the credit card payment. There is nothing we can do if user can't figure out the missing fields.

Do yo have suggestions ?

**Comment by xiaobin15** [comment]
Hi Cheh,
I did not enter any card #, but clicked on "submit". Then user got some error messages as expected. I tried to go back to pay by check, then page was frozen.
Xiaobin

**Comment by chehhoo** [comment]
Thanks XIaobin

Would you please take a screenshot about the issue and paste to issues to make sure I see what you are talking about?

Instruction: You may press print screen from keyboard, and paste into the comments.

Thanks
Cheh
