### ISSUE TITLE
Paid by CC/Debit page does not show Debit option

### ISSUE THREAD

**Issue by xiaobin15** [CCLIFE/cclife-conf-registration-01#64]
When choosing payment option "CC/Debit", the page only shows CREDIT option, DEBIT is missing. If you mean that DEBIT is through paypal, then more instruction should be shown to direct user to get to the DEBIT page.

---

福音大会报名表

Pay by CREDIT
付款方式：信用卡或PayPal

點擊”Pay Now” 進入PayPal網頁

```
信用卡支付者請選擇第二項，無須登入PayPal帳戶
付款後，請點擊 return to GFCC 2015 回到GFCC 2015付款確認頁面
請勿點擊瀏覽器的退回鍵,以免丟失您所有信息。
```

Pay Now with Credit Card or PayPal https://www.sandbox.paypal.com/cgi-bin/webscr

**Comment by chehhoo** [comment]
The debit/credit means you can use credit or debit card to pay. 

There is no separate page for DEBIT. As credit and debit are on same page.

If you are at paypal side, click on option don't have paypal account button should show pay by credit/debit card.

Please see below. Hope this answer your questions:-

![image](https://cloud.githubusercontent.com/assets/9040501/8515311/dbf667d8-2365-11e5-8e5f-1533cf9bbf64.png)

**Comment by chehhoo** [comment]
Xiaobin,

Do you have suggestion to make clearer for user ? Maybe add wording DEBIT side by side with CREDIT ? Does it help ?

Thanks

**Comment by chehhoo** [comment]
The page is on PAYPAL. I believe, this will not issue for us

Here is communication from email

Dear all,

I think handling debt card is the same as credit card. AS LONG AS the debt card has logo for  visa , MasterCard ...

Bill
Sent from my iPhone

On Jul 8, 2015, at 9:58 PM, X. Liu xiaobin_liu@yahoo.com wrote:
Cheh,

You need to choose one of those 4 major CC when you get to that page. Paypal message is misleading, I believe. Then it's not under your control.

I expect to see the fifth option: Debit.

Xiaobin

---

From: Cheh Hoo chehhoo@gmail.com
To: X. Liu xiaobin_liu@yahoo.com; Bill Chan wkychan@aol.com; Wei Cai wcai0@yahoo.com 
Sent: Wednesday, July 8, 2015 8:04 PM
Subject: Re: Payment "Debit" unavailable. Only 4 CC can be chosen.

Thanks for screenshot,  this page is controlled by PayPal, we cannot make change to it . From my understanding,  this page ask you to enter credit card or debit card to make payment.  You can enter credit card or debit card 16 digit number to process the payment. So,  I am not quite sure what you mean debit is unavailable. what do you expect it should show?

On Wed, Jul 8, 2015, 11:49 AM X. Liu xiaobin_liu@yahoo.com wrote:
<img src="https://ci3.googleusercontent.com/proxy/Wdt4Xwh7fJsIXOCbfpEKhmTe72BiSGNFFEtmQHPd1jNYV8Et5pjXH1mhRbR-5uJhczo8NK2Y76TVNoGd_uHn7iojpGvlNn3U3xEyK6hc0xzZcHk4WL88RBg6HiaCgZxexG3Db0SFy9h09Fy9ehVfyMVR78qLlw6_mfn7rBanviT9UCJgiQ3UaoHkLGsTMpc-2eFvF4VCHGAo_UcJryOkZgSU_oXYGImigNEZNT05p1CfZC32UnXyReYeixORHCLOAdhHgrgbh_IM_ErLrvlEGXirnbuATy3QV-Dlc7kEnQmivIMz0jNFlIqkf8V4AZR-OJ2Q3XUqOo4MzmVeLSioLG8EMzYLgm4WcXJIrieIeBwz_B0GRirQqrbukXArMz0lVZ4_sao=s0-d-e1-ft#https://mail.google.com/mail/?ui=2&ik=4ea15baccc&attid=0.1&th=14e6e9282f9af797&view=fimg&rm=14e6e9282f9af797&sz=w1600-h1000&attbid=ANGjdJ9eUV3MeSAmdhwu7Rim4F8EmTBihaM_Bgssbs6QKiVMM7yNR3xOBjgRKPqdsraCCExYGoL_PdPxkKUNdjYnoyz2K9b6ZrM2_1EcUF79E6oz5OOirfi465skuVk&disp=emb&zw">
