### ISSUE TITLE
The  list of US state mixed with Canada ...see comment for details

### ISSUE THREAD

**Issue by Bill-Chan** [CCLIFE/cclife-conf-registration-01#67]
on step 1...
 (a) enter or select all entries except state/Province
 (b) Hit Next>>
 (c) stay on same page with RED message " please enter your state...."
 (d) Hit " select state"
(e) will see some Canadian provinces on the list . Example: Alberta, British Columbia , etc...

**Comment by chehhoo** [comment]
Fixed and update test site on 7/21/2015
