### ISSUE TITLE
Modify "pay by credit page --- High priority

### ISSUE THREAD

**Issue by Bill-Chan** [CCLIFE/cclife-conf-registration-01#85]
Change the message as follows: 

Pay by CREDIT CARD or PayPal     付款方式：信用卡或PayPal
# I authorize CCLiFe to collet xxx.xx from my account.

   我授权生命季刊从我的账号中支取下述金额：xxx.xx

在您点击“Pay Now”进入下一页前，请阅读有关下一页的注意事项：
• 如果您使用信用卡付款，请点击” Don’t have a PayPal account” 按钮，无须登录PayPal账户。
• 请勿点击浏览器的退回键，以免丢失您的所有信息。

Pay now with credit card or PayPal   点击下方按钮付款

Pay Now

**Comment by Bill-Chan** [comment]
The sentence " I authorize CClife to collect ....account" should just the same font size with other words but in Bold only....Sorry I don't know why it changed to larger font

**Comment by chehhoo** [comment]
Updated 7/29
