### ISSUE TITLE
Emails sent to registrants with credit card payment or check (wordings are similar to Ack page #106)-high priority

### ISSUE THREAD

**Issue by Bill-Chan** [CCLIFE/cclife-conf-registration-01#86]
Format for the email will provide later

**Comment by Bill-Chan** [comment]
Email for credit card payment:

[payment complete email credit -new.docx](https://github.com/CCLIFE/cclife-conf-registration-01/files/1072/payment.complete.email.credit.-new.docx)

**Comment by Bill-Chan** [comment]
Email for check payment:

[payment complete email -check.pdf](https://github.com/CCLIFE/cclife-conf-registration-01/files/859/payment.complete.email.-check.pdf)

**Comment by chehhoo** [comment]
Wei, The email file contain Chinese characters in code format. Please use the following link to convert to readable Chinese characters

http://r12a.github.io/apps/conversion/

![image](https://cloud.githubusercontent.com/assets/9040501/8950834/8d03422a-358c-11e5-9fa2-7e593cd5fa88.png)

Copy the the whole HTML with readable Chinese characters, edit in regular HTML editor.

**Comment by chehhoo** [comment]
After edit the HTML text. Use the same tool to convert back to code.

![image](https://cloud.githubusercontent.com/assets/9040501/8950973/149b83c2-358e-11e5-9e61-73ef86840fae.png)

**Comment by weicai2015** [comment]
Cheh:
Can you please just tell me the file name for the code that I need to change? I searched thru all the files there, none of them looks like the email I got for my testing registration.
Thanks,Wei

**Comment by Bill-Chan** [comment]
HI,

Please use the same letter for corrected ack pages for emails pages.....

**Comment by Bill-Chan** [comment]
check this out today
