### ISSUE TITLE
Output registrant information data  (spreadsheet on google drive)with required fields and format -high priority

### ISSUE THREAD

**Issue by Bill-Chan** [CCLIFE/cclife-conf-registration-01#92]
In the current table , found out missing information ( fields) as follows: 
1. Earphone 2. Faith ( Christian ) 3. Devote ( 事奉角色）4.volunteer 5. Need hotel 6. Registration date 7. Payment date 8. Paid by check, PayPal or credit card 9. Health ID 10. Church name ..

Also : (11) payment amount is not there (12) Chinese name cannot be display 

the access master database, field name and format shown below: 
[GFCC 2015 Field Names.pdf](https://github.com/CCLIFE/cclife-conf-registration-01/files/855/GFCC.2015.Field.Names.pdf)

**Comment by chehhoo** [comment]
Update with format according to PDF file - GFCC 2015 Field Names.pdf

Fixed payment amount

No field "Need Hotel","Paid by check", "PayPal or credit card","Health ID"  in PDF

Please see mapping file for the fields

[Mapping File](https://github.com/CCLIFE/cclife-conf-registration-01/blob/master/docs/artifacts/mapping.csv)

First row is fields format according to GFCC 2015 Field Names.pdf (Please update this row)
Second row is field name map to first row.

**Comment by Bill-Chan** [comment]
Following problems have been observed:
(1) Do not display Chinese characters
(2) Wrong information displays on "Earphone" field
(3) No information displays on "Volunteer" field
(4) Church name is not displayed
See picture below:
![img_2088](https://cloud.githubusercontent.com/assets/11229968/8946072/5b386206-355b-11e5-8624-405722e7da3d.png)

**Comment by Bill-Chan** [comment]
Continue......
 (4) Wrong information displays for meal counts (See issue #94)
(5) No date displays on "reg-date" field
![img_2090](https://cloud.githubusercontent.com/assets/11229968/8946372/8975181a-355d-11e5-844f-d008fc953323.png)

**Comment by chehhoo** [comment]
Fixed others. Meal count is for entire registration, not individual. Please close if this is good for now
